# Generated by Django 4.0.1 on 2022-01-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauracja', '0002_dania_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=7)),
                ('przedmioty', models.ManyToManyField(blank=True, related_name='zamow', to='restauracja.Dania')),
            ],
        ),
    ]
