# Generated by Django 4.0.1 on 2022-01-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauracja', '0003_zamow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('obrazek', models.ImageField(upload_to='menu_images/')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tworzenie', models.DateTimeField(auto_now_add=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=7)),
                ('przedmioty', models.ManyToManyField(blank=True, related_name='zamowienie', to='restauracja.Menu')),
            ],
        ),
        migrations.RemoveField(
            model_name='zamow',
            name='przedmioty',
        ),
        migrations.AlterModelOptions(
            name='kategoria',
            options={},
        ),
        migrations.DeleteModel(
            name='Dania',
        ),
        migrations.DeleteModel(
            name='Zamow',
        ),
        migrations.AddField(
            model_name='menu',
            name='kategoria',
            field=models.ManyToManyField(related_name='item', to='restauracja.Kategoria'),
        ),
    ]
