# Generated by Django 4.0.1 on 2022-01-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restauracja', '0004_menu_zamowienie_remove_zamow_przedmioty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategore'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='zamowienie',
            options={'verbose_name': 'Zamowienie', 'verbose_name_plural': 'Zamowienia'},
        ),
    ]
