# Generated by Django 4.0.1 on 2022-01-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restauracja', '0005_alter_kategoria_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
    ]
