# Generated by Django 4.0.1 on 2022-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauracja', '0006_alter_kategoria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='obrazek',
            field=models.ImageField(upload_to='menu_zdjecia/'),
        ),
    ]
