# Generated by Django 4.0.1 on 2022-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauracja', '0007_alter_menu_obrazek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='kategoria',
            field=models.ManyToManyField(related_name='przedmiot', to='restauracja.Kategoria'),
        ),
    ]
