# Generated by Django 4.0.1 on 2022-01-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restauracja', '0008_alter_menu_kategoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zamowienie',
            new_name='Zamawianie',
        ),
    ]
